name: "Awesome Autopilot"
type: "AUTOPILOT"
speechToText:
  productRef: "stt.deepgram"
  config:
    model: "nova-3"
    languageCode: "en-US"
textToSpeech:
  productRef: "tts.elevenlabs"
  config:
    voice: "6gviCf27bOZ2Wml5iZZv"
intelligence:
  productRef: "llm.google"
  config:
    conversationSettings:
      firstMessage: "Hello, I'm the Awesome Autopilot, how can I help you today?"
      systemPrompt: |
        ## Role
        You are an awesome assistant that can talk about anything. You always ask for the user's name before proceeding with the conversation.

        ## Instructions

        Keep your answers short and concise as this is a phone call.

        ## Example Interaction
        User: I want to learn about the meaning of life.

        Assistant: Ok, but first, what's your name?
        User: My name is John Doe. 

        Assistant: Hello John Doe. Life is a journey of love, laughter, and learning.
        User: That's a great answer! Thank you!

        Assistant: You're welcome! Is there anything else I can help you with?
        User: No, that's all.

        Assistant: Thank you for your time. Have a great day! (And use the `hangup` tool to end the call)

      goodbyeMessage: "Thank you so much, bye!"
      systemErrorMessage: "I'm sorry, I didn't understand that. Can you please repeat it?"
      vad:
        activationThreshold: 0.4
        deactivationThreshold: 0.25
        debounceFrames: 4
      idleOptions:
        message: "Are you still there?"
      transferOptions:
        phoneNumber: "+17853178070"
        message: "I will transfer you to a live agent to help you with your request."
    languageModel:
      provider: "google"
      model: "gemini-2.0-flash-lite"
      maxTokens: 240
      temperature: 0.4
    eventsHook:
      # TODO: Replace with your own URL
      url: "https://ac86-47-132-130-31.ngrok-free.app/events"
      headers:
        Content-Type: "application/json"
        Authorization: "Basic REDACTED"
      events: ["all"]
